[global]
# If True, will show a warning when you run a Streamlit-enabled script via "python my_script.py".
# Default: true
showWarningOnDirectExecution = false

# [theme]
# primaryColor="#f63366"
# backgroundColor="#0e1117"
# secondaryBackgroundColor="#31333F"
# textColor="#fafafa"
# font="sans serif"
[theme]
primaryColor="#39a9db"
backgroundColor="#003049"
secondaryBackgroundColor="#31333F"
textColor="#ffffea"
font="sans serif"
